version: '3.7'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:6.2.0
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:6.2.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    depends_on:
      - zookeeper

  eureka:
    build:
      context: ./eureka-server
    image: eureka-server
    ports:
      - "8761:8761"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://localhost:8761/eureka/
      EUREKA_INSTANCE_HOSTNAME: localhost
      SPRING_APPLICATION_NAME: eureka-server

  user-service:
    build:
      context: ./demo
    image: user-service
    ports:
      - "8080:8080"
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka:8761/eureka/
      SPRING_APPLICATION_NAME: user-service
    depends_on:
      - eureka
      - kafka
      - mysql

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3306"  # Change the host port to 3307
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dbname
